### ISSUE TITLE
Unreliable & inaccurate. 

### ISSUE THREAD

**Issue by ghost** [ptrkstr/Devices#19] opened 2022-09-23 22:37 UTC
It seems this library has some tremendous flaws, one being that it produces `"?"` for data that is available at the tip of your fingers via a simple google search or at https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-m1-max-10-core-cpu-32-core-gpu-14-2021-specs.html

**Example:** 

`MacBookPro(gen: "MacBook Pro (14-inch, 2021)", aNum: "?", fccID: "?", iName: "J314cAP", id: "MacBookPro18,4", color: "Silver", storage: "1 TB", mod: "?"),`

**Reality:** 

<img width="861" alt="SS" src="https://user-images.githubusercontent.com/114029182/192065582-155c0ee8-fc76-4e11-8396-d5ba4f5b4ba5.png">

Therefore, corrected: 

`MacBookPro(gen: "MacBook Pro (14-inch, 2021)", aNum: "A2442", fccID: "?", iName: "J314cAP", id: "MacBookPro18,4", color: "Silver", storage: "1 TB", mod: "MKGP3"),`

**Comment by ptrkstr** [comment] 2022-09-24 07:17
Hi @sammycooks999, thanks for your message.
If you read the readme you'll see that this library generates its data from https://www.theiphonewiki.com/wiki/Models

If you found any information missing from theiphonewiki maybe you could be a team player and update it so everyone benefits including this library?

**Comment by ptrkstr** [comment] 2022-09-29 13:54
Closing issue as the problem is the source data.

**Closed as not planned** 2022-09-29 13:54 UTC
